### ISSUE TITLE
Autosave figure sometimes make heatmap to not to show plot

### ISSUE THREAD

**Issue by xhajnal** [xhajnal/DiPS#84]
I found this correlation using this:
https://stackoverflow.com/questions/62084819/exception-in-tkinter-callback-using-shap

the error looks like this
Plotting heatmap of functions ...
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/matej/.pyenv/versions/3.7.6/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 242, in resize
    self.draw()
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1544, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7fe3f64494d0>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/matej/.pyenv/versions/3.7.6/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 242, in resize
    self.draw()
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1544, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7fe3f64494d0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matej/.pyenv/versions/3.7.6/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/matej/.pyenv/versions/3.7.6/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 253, in idle_draw
    self.draw()
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/matej/Git/DiPS/.venv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1544, in _draw
    def _draw(renderer): raise Done(renderer)
matplotlib.backend_bases._get_renderer.<locals>.Done: <matplotlib.backends.backend_agg.RendererAgg object at 0x7fe3f64494d0>
Figure stored here:  /home/matej/Git/DiPS/results/figures/Heatmap_function_1_of_3__26-Oct-2020-12-41-53.png

**Comment by xhajnal** [comment]
hotfixzed by skipping heatmap figure saving
